// Run against a local dev server: node tests/e2e/canvas-hover.mjs http://127.0.0.1:5186
import assert from 'node:assert/strict'
import { chromium } from 'playwright'

const browser = await chromium.launch({ headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  page.setDefaultTimeout(10000)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('https://**/*', route => route.abort())
  await page.goto(process.argv[2] || 'http://127.0.0.1:5186')
  await page.locator('.canvas-stage').waitFor()
  await page.waitForTimeout(1000)
  await page.locator('input[type=file][accept="image/svg+xml,.svg"]').setInputFiles({ name: 'hover.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 300"><rect id="first" x="50" y="50" width="60" height="60" fill="red"/><g transform="translate(150 50)"><rect id="second" width="60" height="60" fill="blue"/></g><line id="line" x1="80" y1="200" x2="250" y2="200" stroke="green" stroke-width="6"/></svg>') })
  const first = page.locator('.svg-wrap #first')
  const second = page.locator('.svg-wrap #second')
  const hover = page.locator('.layer-hover-overlay')
  const selection = page.locator('.selection-overlay').filter({ has: page.locator('.resize-handle-top-left') })
  const settle = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await first.click()
  await settle()
  const selectedRows = await page.locator('.layer-row.selected').allTextContents()
  const selectedBox = await selection.boundingBox()
  const markup = await page.locator('.svg-wrap').innerHTML()
  await second.hover()
  await hover.waitFor()
  assert.deepEqual(await page.locator('.layer-row.selected').allTextContents(), selectedRows, 'hover preserves selection')
  assert.deepEqual(await selection.boundingBox(), selectedBox, 'selected border stays in place')
  assert.equal(await hover.locator('button').count(), 0, 'hover has no handles')
  assert.equal(await hover.evaluate(node => getComputedStyle(node).pointerEvents), 'none')
  const checkBounds = async (target) => {
    const a = await hover.boundingBox()
    const b = await target.evaluate(node => { const r = node.getBoundingClientRect(); return { x: r.x, y: r.y, width: r.width, height: r.height } })
    for (const key of ['x', 'y', 'width', 'height']) assert.ok(Math.abs(a[key] - Math.max(key === 'width' || key === 'height' ? 1 : -Infinity, b[key])) < 1, `hover ${key} matches target`)
  }
  await checkBounds(second)
  await page.screenshot({ path: '/tmp/vecsy-canvas-hover.png' })
  await page.locator('.canvas-toolbar').hover()
  await hover.waitFor({ state: 'detached' })
  await first.hover()
  await settle()
  assert.equal(await hover.count(), 0, 'selected layer has no duplicate hover border')
  await second.click()
  await settle()
  assert.equal(await hover.count(), 0, 'click replaces hover with selection')
  assert.notDeepEqual(await page.locator('.layer-row.selected').allTextContents(), selectedRows)
  assert.equal(await page.locator('.svg-wrap').innerHTML(), markup, 'hover and selection do not edit SVG')
  await page.getByRole('button', { name: /Zoom in|放大/ }).first().click()
  await first.hover()
  await hover.waitFor()
  await checkBounds(first)
  await page.keyboard.press('h')
  await hover.waitFor({ state: 'detached' })
  await first.hover()
  await settle()
  assert.equal(await hover.count(), 0, 'pan tool suppresses hover')
  await page.keyboard.press('v')
  const lineBox = await page.locator('.svg-wrap #line').boundingBox()
  await page.mouse.move(lineBox.x + lineBox.width / 2, lineBox.y)
  await hover.waitFor()
  await settle()
  assert.equal(await hover.getAttribute('data-layer-id'), await page.locator('.svg-wrap #line').getAttribute('data-editor-id'))
  await checkBounds(page.locator('.svg-wrap #line'))
  await second.hover()
  await page.mouse.down()
  const box = await first.boundingBox()
  await page.mouse.move(box.x + 20, box.y + 20, { steps: 5 })
  await settle()
  assert.equal(await hover.count(), 0, 'drag suppresses hover')
  await page.mouse.up()
  assert.deepEqual(errors, [])
  console.log('Canvas hover E2E passed: persistent selection, transformed bounds, leave, click, zoom, pan, line, drag; no page errors')
} finally { await browser.close() }
